# Generated by Django 3.1.8 on 2021-04-20 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_lobby', to=settings.AUTH_USER_MODEL),
        ),
    ]
