# Generated by Django 3.1.8 on 2021-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210420_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='win_state',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
